### ISSUE TITLE
Runtime Exception while invoking VideoUpload in Java APISample

### ISSUE THREAD

**Issue by adityasm96** [Azure-Samples/media-services-video-indexer#80]
Hi Team, 
We are following the Java APISample present in the Repo. We are getting the below runtime issue when invoking the VideoUplaod method. Please find the exception below: 

Exception in thread "main" java.lang.RuntimeException: (POST https://api.videoindexer.ai/accounts/remix-video-indexer/videos?api-version=2022-08-01&videoUrl=https%3A%2F%2Fremixstoargeaccount.blob.core.windows.net%2Fremixblobstorage%2FVideo+Indexer%2FSampleRemix-1.mp4&name=video-345-sample&description=video_description&privacy=private&callbackUrl=&accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJWZXJzaW9uIjoiMi4wLjAuMCIsIktleVZlcnNpb24iOiIxNGU0M2M5NDFlOWI0OTg1OWU0NDkzNDFhZjgxZjNiNiIsIkFjY291bnRJZCI6ImQ4YTYzNDFmLTg3N2QtNGYzMi1iNWVhLTViYzQ0NTJhNzA2ZCIsIkFjY291bnRUeXBlIjoiQXJtIiwiUGVybWlzc2lvbiI6IkNvbnRyaWJ1dG9yIiwiRXh0ZXJuYWxVc2VySWQiOiI3OTE4NUMxRDY4NjI0RkFEODQwRTZBNjU1MzRCRURFOCIsIlVzZXJUeXBlIjoiTWljcm9zb2Z0Q29ycEFhZCIsIklzc3VlckxvY2F0aW9uIjoiY2VudHJhbGluZGlhIiwibmJmIjoxNjg2NjU1NTc0LCJleHAiOjE2ODY2NTk0NzQsImlzcyI6Imh0dHBzOi8vYXBpLnZpZGVvaW5kZXhlci5haS8iLCJhdWQiOiJodHRwczovL2FwaS52aWRlb2luZGV4ZXIuYWkvIn0.MBTlJFb9b4RK2d05anfeYZCGlKwooiy5DghI_ORY2A0EWCpnSlIvuujfA_F2mcooWFGbEtSNNPVTp5XWu6dF2dbAewgLyb22ziHzSvky2p4hVURUYoW-OO8zKWpxehM0QR2mwcqroW4b9Op_PTyw7M5Zd8nVfqi6CWaM-WNoFGsaQX9ePlvrkE_GuiiKOVT1-cJkg7aRqpy_NtOSG-xoGlD30Eb7iNC7xm4gkDCJPcItiuk4sOE9iwINLNnDIMVgY5802H5rsiIisOnx6aaFuaZwSgRanWAvgpTeczRGBYJeS-zunyoLZtWhGhp6NPwhpQdenriD34oleYfwlaObwg) 411
	at apisamples.HttpUtils.Utils.VerifyStatus(Utils.java:54)
	at apisamples.HttpUtils.Utils.httpStringResponse(Utils.java:48)
	at apisamples.VideoIndexerClient.uploadVideo(VideoIndexerClient.java:127)
	at apisamples.App.main(App.java:33)

**Comment by tshaiman** [comment]
yes , this is fixed on Pr : 
https://github.com/Azure-Samples/media-services-video-indexer/pull/81

**Comment by tshaiman** [comment]
resolved
